import numpy as np
marks_1 = np.array([78, 45, 90, 62, 88, 55])
print("Original Marks:", marks_1)
sort_marks = np.sort(marks_1)
print("Sorted Marks:", sort_marks)
print("First element:", marks_1[0])
print("Last element:", marks_1[-1])
print("First 3 marks:", marks_1[0:3])
print("Last 3 marks:", marks_1[3:])
reshaped_marks = marks_1.reshape(2, 3)
print("Reshaped Marks:", reshaped_marks)
print("Data type of array:", marks_1.dtype)
marks_2 = np.array([70, 85, 60])
print("Second Array:", marks_2)
combined_marks = np.concatenate((marks_1, marks_2))
print("Concatenated Array:", combined_marks)